name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: |
  $CHANGES
categories:
  - title: "📦 New Feature"
    labels:
      - "NEW"
      - "Feature"
  - title: "Improvements"
    labels:
      - "IMPROVE"
  - title: "Bug Fixes"
    labels:
      - "FIX"
  - title: "Dependency Updates"
    labels:
      - "Bump"
exclude-labels:
  - "skip-changelog"
